# Generated by Django 2.1.5 on 2019-04-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samsonadejoroscrumy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=200)),
                ('goal_id', models.CharField(default=1, max_length=100)),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samsonadejoroscrumy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsonadejoroscrumy.ScrumUser')),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
                'ordering': ['-goal_id'],
            },
        ),
    ]
