# Generated by Django 2.1.5 on 2019-04-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsonadejoroscrumy', '0002_scrumygoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='moveable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
