# Generated by Django 2.1.5 on 2019-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsonadejoroscrumy', '0003_auto_20190401_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.CharField(max_length=100),
        ),
    ]
